swagger: "2.0"
info:
  description: "Lalalala"
  version: "1.0.0"
  title: "Test MyAPI"
  contact:
    email: "meta@realweb.ru"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8888"
basePath: "/v2"
tags:
- name: "hello"
  description: "Simple Hello Service"

schemes:
- "http"
paths:
 /hello/{username}:
    get:
      tags:
      - "hello"
      summary: "Hello for user"
      description: "Returns a single pet"
      operationId: "helloUsername"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "Name of user"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Hello"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
      security:
      - api_key: []
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  HelloResponse:
    type: "object"
    properties:
      message:
        type: "string"
        description: "hello message for user"
    xml:
      name: "HelloResponse"
externalDocs:
  description: "My docs"
  url: "http://developers.realweb.ru"